### ISSUE TITLE
Typescript declarations

### ISSUE THREAD

**Issue by jrson83** [song940/tiny-matter#2]
Hey, thanks for merging!

I'm creating a [Vite](https://vitejs.dev/) Plugin for auto generating a routes object from `yaml`.
If it's okay, I would create Typescript declarations for tiny-matter and add prettier?

**Comment by lsongdev** [comment]
@jrson83 Sounds good, pull request are welcome.

**Comment by jrson83** [comment]
hey @song940, could you accept PR #3?
It is just about some code refactoring using [prettier](https://prettier.io/).
After I would add the typings.

**Comment by jrson83** [comment]
Thank you!

If you accept the new PR #4, can you please release the new package to NPM?
